### POST
POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2VAbWlrZS5jb20iLCJpZCI6MSwiaWF0IjoxNjg5ODY0MTI2fQ.7A-MdZEYmQ7AFifc3wgXNb0pJNIElX6uCN6Z3gBwhqY
Content-Type: application/json

{
  "author": "Pete Degal",
  "url": "https://overreacted.io/npm-audit-broken-by-design",
  "title": "Title of the blog",
  "year": 2001
}

### DELETE
DELETE http://localhost:3001/api/blogs/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2VAbWlrZS5jb20iLCJpZCI6MSwiaWF0IjoxNjg5ODY0MTI2fQ.7A-MdZEYmQ7AFifc3wgXNb0pJNIElX6uCN6Z3gBwhqY


### PUT
PUT http://localhost:3001/api/blogs/3
Content-Type: application/json

{
  "likes": 15
}