### POST
POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2VAbWlrZS5jb20iLCJpZCI6NCwiaWF0IjoxNjg5NjA1MzgwfQ.ON4C1IZrlg2a_8BgA2QmMALI-NYApCRt0YnMa4XzjGw
Content-Type: application/json

{
  "author": "Someone",
  "url": "https://overreacted.io/npm-audit-broken-by-design",
  "title": "This is the title"
}

### DELETE
DELETE http://localhost:3001/api/blogs/4

### PUT
PUT http://localhost:3001/api/blogs/2
Content-Type: application/json

{
  "likes": 7
}